// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// `vercel env pull` grava em .env.local, que o dotenv não lê por padrão — sem isto os
// comandos do Prisma CLI rodam sem DATABASE_URL. dotenv nunca sobrescreve variáveis já
// definidas, então na Vercel o ambiente real continua tendo precedência.
loadEnv({ path: ".env.local" });
loadEnv();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations exigem conexão direta: o advisory lock que o `migrate deploy` usa não
    // sobrevive ao pooler do Neon, que devolve a sessão ao pool entre statements e faz
    // o lock expirar (P1002). O runtime, em `src/lib/prisma.ts`, segue no pooler.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
